### ISSUE TITLE
Smithing table inventory size is not updated

### ISSUE THREAD

**Issue by lordtgm** [hollow-cube/minestom-ce#110]
In 1.20 update, smithing tables got an additional slot for smithing templates. however this is not updated and minestom still has 3 registered slots for it. (line 28) the number of slots should be 4 instead of 3.
https://github.com/hollow-cube/minestom-ce/blob/78cb62fa72906907aa29d6523095967ccc0bf4ae/src/main/java/net/minestom/server/inventory/InventoryType.java#L6-L31

**Comment by mworzala** [comment]
Fixed in #92
