### ISSUE TITLE
`InstanceContainer#copy()` does not work for unloaded instances

### ISSUE THREAD

**Issue by zax71** [hollow-cube/minestom-ce#140]
If you use an `InstanceContainer` that has not yet been loaded when copying it, the resultant `InstanceContainer` will be empty. To get around this, I can use `InstanceContainer#loadChunk()` but imo `InstanceContainer#copy()` should do this automatically

**Comment by mworzala** [comment]
This is expected behavior. You need to load the chunks you want to copy. 

Loading them automatically does not make much sense. In most cases there is not a simple way to know all of the chunks, and loading them all is unnecessary at best, problematic at worst if it's a big world.
