### ISSUE TITLE
world load error 1.20

### ISSUE THREAD

**Issue by TheSerumDev** [hollow-cube/minestom-ce#19]
InstanceContainer instance = MinecraftServer.getInstanceManager().createInstanceContainer(DimensionType.OVERWORLD);
instance.setChunkLoader(new AnvilLoader(Path.of("worlds/world")));

instance.enableAutoChunkLoad(true);

int chunkRadius = 5;
for (int x = -chunkRadius; x < chunkRadius; x++) {
	for (int y = -chunkRadius; y < chunkRadius; y++) {
		instance.loadChunk(x, y);
	}
}
hey, i'll try to load a spigot 1.20 world but i got the following errors:

-- Log --
https://hastebin.com/share/oyowigazec.php

what can i do, to load a spigot 1.20 world?

**Comment by mworzala** [comment]
Waiting on a Hephaistos update to support anvil 1.20
