### ISSUE TITLE
Host own javadoc

### ISSUE THREAD

**Issue by CodeDoctorDE** [hollow-cube/minestom-ce#38]
Hello,
I saw this project and thanks for maintaining the minestom project!
The readme mentions breaking changes to the minestom codespace.
It would be nice if this project has it's own javadoc.

The javadoc can be hosted using github pages: https://stackoverflow.com/a/74718164

**Comment by mworzala** [comment]
https://javadoc.hollowcube.net/minestom-ce/

**Comment by CodeDoctorDE** [comment]
Thank you very much!
The readme links need to be changed
