### ISSUE TITLE
Error when connecting to the server with 1.20.1: NotificationCenter.send

### ISSUE THREAD

**Issue by CodeDoctorDE** [hollow-cube/minestom-ce#45]
Hello,

I just switched the dependency minestom to minestom-ce (`dev.hollowcube:minestom-ce:a99fdee831`).
I tried to connect to the server with the 1.20.1 (without mods, just vanilla) and got this error message: packet (yt) was larger than I expected, found 6 bytes extra whilst reading packet.

Screenshot:
![Screenshot_20230805_195102](https://github.com/hollow-cube/minestom-ce/assets/20452814/6bcd75af-2fb8-4685-b3e8-9d78ba155d3c)

**Comment by CodeDoctorDE** [comment]
NotificationCenter.send don't work on 1.20.1

**Comment by mworzala** [comment]
Fixed in https://github.com/hollow-cube/minestom-ce/commit/1f87f26b4f4dcd8c6b3f427f8e47379f1510699f
