### ISSUE TITLE
Recipe problem

### ISSUE THREAD

**Issue by josemoncab** [hollow-cube/minestom-ce#67]
Hi, im trying to make recipes for my server but when I try to join the server sometimes i get this.
![imagen](https://github.com/Minestom/Minestom/assets/34101063/568e2d99-dee8-460c-b420-e28dbe6bfff3)

Looking in the packets i found that the packet it sends doesnt contain any data with the ingredients or the result. 
![imagen](https://github.com/Minestom/Minestom/assets/34101063/1bee375c-6a91-4bfe-8615-f1d2d4593051)

Same packet from a paper server (only choose une recipe)
![imagen](https://github.com/Minestom/Minestom/assets/34101063/e09ae88f-9a0f-464c-9c52-6f742c926d0f)

Trough testing I found some problems
The test is done only in minestom-ce version 5bcc72b911

- BlastingRecipe: The declared_recipes packet not sent, a NullPointerException from a NetworkBuffer$Writer, can join the server
- CampfireCookingRecipe: The declared_recipes packet not sent, a NullPointerException from a NetworkBuffer$Writer, can join the server
- ShapedRecipe: "Loading NBT data" message in the client, declared_recipes sent without data only type and recipeID
- ShapelessRecipe: "Loading NBT data" message in the client, declared_recipes sent without data only type and recipeID
- SmeltingRecipe: The declared_recipes packet not sent, a NullPointerException from a NetworkBuffer$Writer, can join the server
- SmithingRecipe: "Unknow recipe serializer minecraft:smithing" message in the client, declared_recipes sent without data only type and recipeID
- SmokingRecipe: The declared_recipes packet not sent, a NullPointerException from a NetworkBuffer$Writer, can join the server
- StonecutterRecipe: The declared_recipes packet is sent without data only type and recipeID, can join the server

The code of the recipes
https://gist.github.com/josemoncab/32191389a549edb7ddf7fdc70a6c9397

Main class code
```java
public static void main(String[] args) {
        System.setProperty("minestom.use-new-chunk-sending", "true");

        MinecraftServer minecraftServer = MinecraftServer.init();

        MinecraftServer.getRecipeManager().addRecipe(new Recipes.Blasting()); // Change to diferent recipes

        PlayerInit.init(); // Class from the demo server

        minecraftServer.start("0.0.0.0", 25565);
    }
```

**Comment by KrystilizeNevaDies** [comment]
It seems to me that the data is still sent, just in an incorrect way.
e.g. see the PacketWriteReadTest that is still passing.

**Comment by KrystilizeNevaDies** [comment]
![image](https://github.com/hollow-cube/minestom-ce/assets/57762380/b6ca1d27-2b87-44a8-bff7-df926315acd6)
we do not have the recipe category
