### ISSUE TITLE
incorrect shulker meta

### ISSUE THREAD

**Issue by MelonHell** [hollow-cube/minestom-ce#75]
val meta = shulker.entityMeta as ShulkerMeta
meta.shieldHeight = 10

instead of changing the height of the shield, the color of the shulker changes
![image](https://github.com/hollow-cube/minestom-ce/assets/53826469/4c567fbb-b50a-4906-8ab4-4b31db91d8f3)

**Comment by MelonHell** [comment]
this bug is missing in #68

**Comment by mworzala** [comment]
What do you mean by missing? Its fixed? Or also present in 1.20.2?

**Comment by MelonHell** [comment]
Oh sorry. It seems I was wrong. The bug is still there
